name: ride_share_driver
description: A new Flutter application.


publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter



flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Brand-Bold
      fonts:
        - asset: assets/fonts/bolt-semibold.ttf
        - weight: 700
    - family: Brand-Regular
      fonts:
        - asset: assets/fonts/bolt-regular.ttf

